{% set data = load_setup_py_data() %}


package:
  name: ctapipe
  version: {{ data.get('version') }} # auto-fetch version from package
  

source:
  #path_url:
  # which branch/tag to use (should be a vX.X release)
  git_rev: v0.6.2
  git_url: https://github.com/cta-observatory/ctapipe.git

  
build:
  number: 1
   
  entry_points:
    # should be identical to the entry_points in ctapipe's setup.py
    - ctapipe-info = ctapipe.tools.info:main
    - ctapipe-camdemo = ctapipe.tools.camdemo:main
    - ctapipe-dump-triggers = ctapipe.tools.dump_triggers:main
    - ctapipe-flow = ctapipe.flow.flow:main
    - ctapipe-chargeres-extract = ctapipe.tools.extract_charge_resolution:main
    - ctapipe-chargeres-plot = ctapipe.tools.plot_charge_resolution:main
    - ctapipe-chargeres-hist = ctapipe.tools.plot_charge_resolution_variation_hist:main
    - ctapipe-dump-instrument = ctapipe.tools.dump_instrument:main
    
requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - setuptools
  host:
    - python 
    - astropy >=1.3
    - bokeh >=1.0.1
    - eventio 0.11.0
    - iminuit
    - matplotlib
    - numba
    - numpy
    - pandas
    - psutil
    - pyhessio >=2.1
    - pytables
    - pytest-runner
    - scikit-learn
    - scipy >=0.19
    - tqdm
    - traitlets
  run:
    - python 
    - astropy >=1.3
    - ctapipe-extra >=0.2.9,<0.3
    - cython
    - eventio 0.11.*
    - graphviz
    - iminuit
    - matplotlib >=1.3
    - numba
    - pandas
    - psutil
    - pyhessio >=2.1
    - pytables
    - pytest
    - pytest-runner
    - pyyaml
    - pyzmq
    - scikit-image
    - scikit-learn
    - scipy
    - tqdm
    - traitlets
test:
  imports:
     - ctapipe
     - ctapipe.io 
     - ctapipe.core
     - ctapipe.coordinates
     - ctapipe.instrument
     - ctapipe.visualization
     - ctapipe.tools
     - ctapipe.utils
     - ctapipe.reco
  commands:
     - ctapipe-info --version

about:
  home: https://github.com/cta-observatory/ctapipe
  license: BSD
  summary: "Prototype framework for CTA low-level data processing"
