{% set data = load_setup_py_data() %}

package:
  name: ctapipe-extra
  version: {{ data.get('version') }}
  

source:
  #url: https://github.com/cta-observatory/ctapipe-extra/archive/v0.2.6.tar.gz
  #git_rev: master
  #git_url: https://github.com/cta-observatory/ctapipe-extra.git
  path: /Users/kosack/Projects/CTA/Working/ctapipe-extra
  
build:
  noarch: python
  # string has to have just py in it for noarch build to work
  #string: py_0

requirements:
  build:
    - setuptools

about:
  home: https://github.com/cta-observatory/ctapipe-extra
  license: BSD
